query GetMyRentAds($input: MyApartmentAdsRequest!) {
  rentAd__myRentAd_unionRentPeriods(input: $input) {
    apartmentAdLongTermRent {
      apartmentAdId
      status
      apartmentAd {
        ...myApartmentFragment
        longTermRent {
          id
          isApproved
          cost
          ownershipDocuments
          declineReason
        }
        completeStep
      }
    }
    apartmentAdShortTermRent {
      apartmentAdId
      status
      apartmentAd {
        ...myApartmentFragment
        shortTermRent {
          id
          rentBookingType
          isApproved
          lockedDates {
            endDate
            startDate
          }
          bookingAccessInMonths
          cost
          declineReason
        }
        completeStep
      }
    }
  }
}
