export const ads = {
  ACTIVE: [
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'ACTIVE',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'ACTIVE',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'ACTIVE',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'ACTIVE',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'ACTIVE',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
  ],
  PUBLISHED: [
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'PUBLISHED',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'PUBLISHED',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
  ],
  PROCESSING: [
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'PROCESSING',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: false,
      payMethod: false,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'PROCESSING',
      confirmData: true,
      confirmPhone: true,
      confirmDocuments: true,
      confirmed: true,
      payMethod: true,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'PROCESSING',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: false,
      payMethod: false,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'PROCESSING',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: false,
      payMethod: false,
    },
  ],
  PAUSED: [
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'PAUSED',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: false,
      payMethod: false,
    },
  ],
  DRAFT: [
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'LONG',
      status: 'DRAFT',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: true,
      payMethod: false,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'DRAFT',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: true,
      payMethod: false,
    },
    {
      pictureSrc: '/img/apart.png',
      title: 'Уютная квартира в центре Астана',
      address: 'Астана, ул. Сауран, 7',
      price: '12 000',
      rentType: 'SHORT',
      status: 'DRAFT',
      confirmData: false,
      confirmPhone: true,
      confirmDocuments: false,
      confirmed: false,
      payMethod: false,
    },
  ],
};
