export const requests = [
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    message: 'tratata',
    apartmentsName: 'Уютная квартира в центре Астана',
    dateStart: '13 мая 1975',
    dateEnd: '19 мая 1975',
    numberOfAdults: 2,
    numberOfChilds: 1,
    numberOfPets: 1,
    rentType: 'SHORT',
  },
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    apartmentsName: 'Уютная квартира в центре Астана',
    dateStart: '13 мая 1975',
    dateEnd: '19 мая 1975',
    numberOfAdults: 0,
    numberOfChilds: 0,
    numberOfPets: 101,
    rentType: 'SHORT',
  },
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    apartmentsName: 'Уютная квартира в центре Астана',
    dateStart: '13 мая 1975',
    dateEnd: '19 мая 1975',
    numberOfAdults: 2,
    numberOfChilds: 0,
    numberOfPets: 1,
    rentType: 'SHORT',
  },
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    apartmentsName: 'Уютная квартира в центре Астана',
    numberOfAdults: 20,
    numberOfChilds: 0,
    numberOfPets: 0,
    rentType: 'LONG',
  },
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    apartmentsName: 'Уютная квартира в центре Астана',
    numberOfAdults: 20,
    numberOfChilds: 0,
    numberOfPets: 0,
    rentType: 'LONG',
  },
  {
    avatar: '/img/userPic.png',
    name: 'Азамат Мусагалиев',
    verifiedUser: false,
    apartmentsName: 'Уютная квартира в центре Астана',
    numberOfAdults: 20,
    numberOfChilds: 0,
    numberOfPets: 0,
    rentType: 'LONG',
  },
];
