export const mockCards = [
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
  {
    rentType: 'Квартира целиком',
    guestsNum: '1',
    bedNum: '1',
    bathNum: '1',
    pictureSrc: '/img/apart.png',
    title: 'Уютная квартира в центре Астаны',
    price: '12000',
    address: 'Астана, ул. Сауран, 7',
  },
];
export const mockFilters = [
  { title: 'Моментальное бронирование', id: 1 },
  { title: 'Бесплатная парковка', id: 2 },
  { title: 'Можно курить', id: 3 },
  { title: 'Вечеринки разрешены', id: 4 },
  { title: 'Можно с питомцами', id: 5 },
];
