query GetApartmentsIdentificatorByApIds($input: FindApartmentAdsIdentificatorsRequest!) {
  rentAdIdentificators__findByRentIds(input: $input) {
    slugs {
      id
      slug
      apartmentId
    }
  }
}
