query getActiveContractById($input: FindContractRequest!) {
  contract__tenant_find(input: $input) {
    arrivalDate
    departureDate
    cost
    apartmentAdId
    innopayCardId
    contractCancelation {
      id
    }
    nextPayment {
      id
      contractId
      withdrawFundsDate
    }
    guests {
      numberOfAdult
      numberOfChildren
    }
    shortTermRentCancellationPolicyType
    baseApartmentAdData {
      address {
        city
        street
        houseNumber
      }
      title
    }
    rules {
      allowedWithPets
      allowedWithChildren
      allowedToSmoke
      allowedToHangingOut
    }
    apartmentRentPeriodType
    apartmentAd {
      id
      shortTermRent {
        id
      }
      longTermRent {
        id
      }
      address {
        lat
        lng
        city
        street
        houseNumber
      }
      photos {
        fileKey
      }
    }
    landlord {
      id
      avatarKey
      firstName
      lastName
    }
    tenant {
      avatarKey
      firstName
      lastName
    }
  }
}
