query GetCancellationInfo($input:TenantContractCancelationInfoRequest!){
    contract__tenant_cancelationInfo(input: $input){
        cancelationDate
        checkOutDate
        checkoutType
        refundsAmount
        strategyType
        withdrawalAmount
        recomputedLastStayWithdrawalAmount
    }
}