fragment apartmentLandlordFragment on UserModel {
  avatarKey
  birthDate
  createdAt
  deletedAt
  firstName
  gender
  id
  isIdentityApproved
  isPhoneApproved
  lastName
  middleName
  updatedAt
}
