fragment apartmentContractRequestFragment on ContractRequestModel {
  apartmentAdId
  apartmentRentPeriodType
  arrivalDate
  createdAt
  deletedAt
  departureDate
  guests {
    numberOfAdult
    numberOfChildren
    numberOfPets
  }
  id
  status
  tenantId
  updatedAt
}
