fragment myApartmentFragment on ApartmentAdModel {
  id
  innopayCardId
  rentPeriodType
  landlord {
    id
    identityDocuments
    isPhoneApproved
    identityStatus
  }
  photos {
    fileKey
  }
  description {
    name
  }
  address {
    city
    street
    houseNumber
  }
}
