export const AppConfig = {
  ENV: process.env.ENV,
  GQL_API_URL: process.env.GQL_API_URL,
  REST_API_URL: process.env.REST_API_URL,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  REACT_APP_GOOGLE_OAUTH_CLIENT_ID: process.env.REACT_APP_GOOGLE_OAUTH_CLIENT_ID,
  REACT_APP_GOOGLE_OAUTH_CLIENT_SECRET: process.env.REACT_APP_GOOGLE_OAUTH_CLIENT_SECRET,
};
