query GetShortTermRentByApId($id: FindShortTermRentAdRequest!) {
  rentAd__find_shortTermAdByApartmentId(input: $id) {
    data {
      apartmentAdId
      arrivalTime
      bookingAccessInMonths
      cancellationPolicy
      cost
      createdAt
      currency
      declineReason
      deletedAt
      departureTime
      id
      isApproved
      lockedDates {
        endDate
        startDate
      }
      rentBookingType
      status
      updatedAt
      apartmentAd {
        address {
          city
          country
          houseNumber
          lat
          lng
          region
          street
        }
        apartmentType
        apartmentCategory
        contractRequests {
          id
          apartmentAdId
          apartmentRentPeriodType
          arrivalDate
          createdAt
          deletedAt
          departureDate
          guests {
            numberOfAdult
            numberOfChildren
            numberOfPets
          }
          status
          tenantId
          updatedAt
          contract {
            id
            status
          }
        }
        createdAt
        defaultPaymentMethod
        deletedAt
        description {
          description
          forFamily
          freeParking
          name
          quite
          remoteView
          selfCheckIn
          workSpace
        }
        characteristics {
          ceilingHeight
          floor
          gas
          gasSupply
          heating
          landArea
          light
          objectArea
          objectPlacement
          sewerage
          territoryArea
          totalArea
          ventilation
          water
          waterSupply
          yearOfConstruction
        }
        details {
          numberOfRooms
          numberOfGuests
        }
        id
        landlord {
          avatarKey
          birthDate
          createdAt
          deletedAt
          firstName
          gender
          id
          isIdentityApproved
          isPhoneApproved
          lastName
          middleName
          updatedAt
        }
        landlordId
        photos {
          fileKey
          order
        }
        rentPeriodType
        rules {
          allowedToHangingOut
          allowedToSmoke
          allowedWithChildren
          allowedWithPets
        }
        updatedAt
        videos {
          fileKey
          order
        }
      }
    }
    averageResponseOnRequest {
      days
      hours
      seconds
      minutes
      milliseconds
    }
  }
}
